name: js-Actions

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
        - name: list files
          run: |
            pwd
            ls -a
        - name: checkout repo
          uses: actions/checkout@v2
        - name: list files
          run: |
            pwd
            ls -a
        - name: simple js action
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: 'Donda'
        - name: Log gretting time
          run: echo "Greeting time is ${{ steps.greet.outputs.time }}"
